[package]
name = "echo-server"
version = "0.1.0"
authors = ["Lloyd Anthony Ganal Balisacan <lloydganal@andorra.ad>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
echo-protocol = {path = "../echo-protocol"}